Update aws_access_secret_terraform.yml - make it simpler

diff --git a/.github/workflows/aws_access_secret_terraform.yml b/.github/workflows/aws_access_secret_terraform.yml
--- a/.github/workflows/aws_access_secret_terraform.yml
+++ b/.github/workflows/aws_access_secret_terraform.yml
@@ -1,90 +1,49 @@
 name: "learn-aws-wordpress-ec2"
 
 on:
- push:
-   branches: [ "main" ]
- pull_request:
-   branches: [ "main" ]
+  push:
+    branches: [ "main" ]
+  pull_request:
+    branches: [ "main" ]
 
 env:
- # verbosity setting for Terraform logs
- TF_LOG: INFO
- # Credentials for deployment to AWS
- AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_POC }}
- AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_POC }}
+  # verbosity setting for Terraform logs
+  TF_LOG: INFO
+  # Credentials for deployment to AWS
+  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_POC }}
+  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_POC }}
 
 jobs:
- terraform:
-   name: "learn-aws-wordpress-ec2"
-   runs-on: ubuntu-latest
-   defaults:
-     run:
-       shell: bash
+  terraform:
+    name: "learn-aws-wordpress-ec2"
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash
 
-   steps:
-     - name: Checkout the repository to the runner
-       uses: actions/checkout@v2
+    steps:
+      - name: Checkout the repository
+        uses: actions/checkout@v2
 
-     - name: Setup Terraform with specified version on the runner
-       uses: hashicorp/setup-terraform@v2
-       with:
-         terraform_version: 1.3.0
-  
-     - name: Terraform init
-       id: init
-       run: terraform init
+      - name: Setup Terraform
+        uses: hashicorp/setup-terraform@v2
+        with:
+          terraform_version: 1.3.0
 
-     - name: Terraform format
-       id: fmt
-       run: terraform fmt
+      - name: Initialize Terraform
+        run: terraform init
 
-     - name: Terraform validate
-       id: validate
-       run: terraform validate
+      - name: Format Terraform files
+        run: terraform fmt
 
-     - name: Terraform plan
-       id: plan
-       if: github.event_name == 'pull_request'
-       run: terraform plan -var-file="terraform.tfvars.json" -no-color -input=false
-       continue-on-error: true
+      - name: Validate Terraform configuration
+        run: terraform validate
 
-     - uses: actions/github-script@v6
-       if: github.event_name == 'pull_request'
-       env:
-         PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
-       with:
-         script: |
-           const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
-           #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
-           #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
-           #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
-
-           <details><summary>Show Plan</summary>
-
-           \`\`\`\n
-           ${process.env.PLAN}
-           \`\`\`
-
-           </details>
-           *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
-
-           github.rest.issues.createComment({
-             issue_number: context.issue.number,
-             owner: context.repo.owner,
-             repo: context.repo.repo,
-             body: output
-           })
-
-     - name: Terraform Plan Status
-       if: steps.plan.outcome == 'failure'
-       run: exit 1
-
-     - name: Terraform Apply
-       if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-       run: |
-         terraform apply -var-file="terraform.tfvars.json" -auto-approve -input=false || export BUILD_FAILED=true
-         if [ "$BUILD_FAILED" == "true" ]; then
-           echo "Build failed, sending alert and triggering destroy"
-           terraform destroy -var-file="terraform.tfvars.json" -auto-approve -input=false
-           exit 1
-         fi
+      - name: Apply Terraform configuration
+        run: |
+          terraform apply -var-file="terraform.tfvars.json" -auto-approve -input=false || export BUILD_FAILED=true
+          if [ "$BUILD_FAILED" == "true" ]; then
+            echo "Build failed, sending alert and triggering destroy"
+            terraform destroy -var-file="terraform.tfvars.json" -auto-approve -input=false
+            exit 1
+          fi
