Update aws_access_secret_terraform.yml - added if else destroy tf

diff --git a/.github/workflows/aws_access_secret_terraform.yml b/.github/workflows/aws_access_secret_terraform.yml
--- a/.github/workflows/aws_access_secret_terraform.yml
+++ b/.github/workflows/aws_access_secret_terraform.yml
@@ -32,7 +32,7 @@ jobs:
   
      - name: Terraform init
        id: init
-       run: terraform init -backend-config="bucket=$BUCKET_TF_STATE"
+       run: terraform init
 
      - name: Terraform format
        id: fmt
@@ -45,7 +45,7 @@ jobs:
      - name: Terraform plan
        id: plan
        if: github.event_name == 'pull_request'
-       run: terraform plan -no-color -input=false
+       run: terraform plan -var-file="terraform.tfvars.json" -no-color -input=false
        continue-on-error: true
 
      - uses: actions/github-script@v6
@@ -81,4 +81,10 @@ jobs:
 
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-       run: terraform apply -var-file="terraform.tfvars.json" -auto-approve -input=false
+       run: |
+         terraform apply -var-file="terraform.tfvars.json" -auto-approve -input=false || export BUILD_FAILED=true
+         if [ "$BUILD_FAILED" == "true" ]; then
+           echo "Build failed, sending alert and triggering destroy"
+           terraform destroy -var-file="terraform.tfvars.json" -auto-approve -input=false
+           exit 1
+         fi
