Update aws_access_secret_terraform.yml

diff --git a/.github/workflows/aws_access_secret_terraform.yml b/.github/workflows/aws_access_secret_terraform.yml
--- a/.github/workflows/aws_access_secret_terraform.yml
+++ b/.github/workflows/aws_access_secret_terraform.yml
@@ -72,5 +72,10 @@ jobs:
           git status          
           git add state
           git commit -m "Random tfstate"
-          git push origin destroy/main
+          git push https://$GIT_ACCESS_KEY:$GIT_SECRET_ACCESS_KEY@repository_url destroy/main || export BUILD_FAILED=true
+          if [ "$BUILD_FAILED" == "true" ]; then
+            echo "Build failed, sending alert and triggering destroy"
+            terraform destroy -var-file="terraform.tfvars.json" -auto-approve -input=false
+            exit 1
+          fi       
           terraform destroy -var-file="terraform.tfvars.json" -auto-approve -input=false
